### ISSUE TITLE
After activation the sessions are still in file

### ISSUE THREAD

**Issue by eniac111** [keerati/odoo-redis#1]
Hello Keerati,

After I activate the module, Odoo still keeps the sessions under the "/sessions" folder. There are not any error logs. I'm testing it with Odoo 8. Does it work for you? 

Regards,
Blagovest Petrov

**Comment by keerati** [comment]
After activating the module, can you try restarting the Odoo process again?

I tested the module with Odoo 9. haven't check with Odoo 8 yet.

**Comment by harunyasar** [comment]
@keerati i try to test with odoo 9 all static files are not working.

**Comment by eniac111** [comment]
Yes, I tried to restart it. Nothing..

@harunyasar check your $PYTHONPATH env variable.

**Comment by harunyasar** [comment]
@eniac111 it does not move the all old sessions from sessions folder to redis. you can try to delete old session files from this folder then try it again. probably you'll see sessions folder is empty and the new session key-value pairs in your redis instance.

**Comment by keerati** [comment]
@eniac111 what @harunyasar explained above is correct. The code does not handle the existing sessions storing on file system. The new sessions after activating the module should be stored on Redis. And after looking through the code of Odoo 8 (https://github.com/odoo/odoo/tree/8.0), it should work.

@harunyasar Do you get any error in the log that I can look at? I have no idea how this module relates to the static files.

**Comment by harunyasar** [comment]
@keerati the problem was my docker container. i tried once again with updated odoo repository and it worked. thanks for your support.

**Comment by eniac111** [comment]
@keerati The problem still persists in Odoo 8 but I'll do a more detailed test with the official Docker image in the weekend.

**Comment by keerati** [comment]
I will close this issue for now. If the problem still persists, feel free to open it again.
